### ISSUE TITLE
[# 7 TES 1.1 Spec compliance]  Adding streamable flag to tesInput

### ISSUE THREAD

**Issue by vsmalladi** [microsoft/ga4gh-tes#12]
Adding streamable flag to tesInput [CoA PR 444](https://github.com/microsoft/CromwellOnAzure/pull/444)

**Comment by jgainerdewar** [comment]
Relevant tool to test with: https://gatk.broadinstitute.org/hc/en-us/articles/360036883491-GenomicsDBImport

**Comment by BMurri** [comment]
This was regressed by #404
