### ISSUE TITLE
Root cause of TES task failure not being included in TES task logs

### ISSUE THREAD

**Issue by MattMcL4475** [microsoft/ga4gh-tes#125]
There are cases where the specific error message goes into the TES application insights logs, but not the TES task logs.  For example, when a specific VM type isn't available. This is a problem because end users in Terra won't know what the root cause error is, since we can generally assume they only will get error information from whatever is sent back to Cromwell via TES.  We should assume end users won't be accessing Application Insights.

**Comment by MattMcL4475** [comment]
Basically same issue for TriggerService: {
  "WorkflowUrl": "https://raw.githubusercontent.com/microsoft/gatk4-somatic-snvs-indels-azure/az2.7.0/mutect2.wdl",
  "WorkflowInputsUrl": "https://raw.githubusercontent.com/microsoft/gatk4-somatic-snvs-indels-azure/az2.7.0/mutect2.inputs.json",
  "WorkflowInputsUrls": null,
  "WorkflowOptionsUrl": null,
  "WorkflowDependenciesUrl": null,
  "WorkflowFailureInfo": {
    "WorkflowFailureReason": "CromwellFailed"
  }
}

**Comment by BMurri** [comment]
Many (most?) task-specific errors are now added to TES task logs, but the code has not be evaluated to ensure that all errors leading to task failure are logged there. Furthermore, no comprehensive assessment has been made to evaluate either the effectiveness or the accuracy of the reports being made.

**Comment by MattMcL4475** [comment]
Closing for now, until a new specific error occurs that fits this pattern
