### ISSUE TITLE
Implement download and upload operations in TES scheduler via the TES Task runner

### ISSUE THREAD

**Issue by giventocode** [microsoft/ga4gh-tes#144]
**Overview**
The TES Task runner provides the ability to download and upload files using the a SAS URL. The goal of this story is to retrofit the existing batch scheduler implementation to use this functionality. 

AC:
 - Must remove the dependency with `blobxfer` for download/upload.
 - Must define how the TES Task runner will be deployed to the Batch Node. 
   -  A possible approach would consist of deploying the runner and its tasks definition file as  Batch resources.
 - Must use the SAS resolution strategy of `None` - just-in-time SAS resolution is follow up work.
 - Should maintain the existing functionality for DRS.
 - Should maintain the existing approach where the SAS tokens are generated upfront by the TES server.
 - Should consider using the `upload` and `download` commands of the runner. 

 
 DoD:
- Code is merged into main, and all integration tests pass.

**Comment by MattMcL4475** [comment]
1.  Publish the TES.Runner and TES.RunnerCLI in Dockerfile-TES and put them in the TesAPI.Web/scripts folder.
2.  On startup, upload the binaries to Azure Storage if they don't already exist (maybe use MD5 hash and set the blobs content-md5.  Keep it simple)
3.  When the Batch node task begins, download the binaries
