### ISSUE TITLE
[Feature] Implement TES Task Runner 

### ISSUE THREAD

**Issue by giventocode** [microsoft/ga4gh-tes#148]
**Overview**
TES dynamically creates a batch script when a new task is submitted. This approach presents several challenges such as:
- Current implementation is hard to maintain and enhance - code that generates code is complex.
  -  New enhancements such as #126 , is challenging to implement considering al possible code paths - ARM, Terra, DRS, etc. 
  -  Robust testing to validate this functionality in isolation is not available and impractical to implement - issue: #62 
- No straightforward way to stream log data as the task is executed #212.
- No feasible way to stream log data as the task is executed.
- Download and upload operations are performed sequentially.
- Download from S3 or GCP sources are hard to implement. 

**Solution**
The proposed solution is to create a new executable that runs on the Batch node that controls download/upload operations as well as the execution of commands.  The following is the AC for the feature:

 - Must enable download and upload operations for all scenarios and resolution approaches.
 - Must remove the dependency with the `blobxfer` and the `docker` containers. 
 - Must determine best way to deploy the executable on the Batch Node.
 - Must allow for the execution of commands on containers. 
 - Consider starting once when the node starts running, and only exiting when the node is deallocated.  Abandon use of Azure Batch task ontology for task execution, and instead have nodes dequeue tasks from a queue (evaluate both Service Bus Queues and Storage Queues).  This will minimize wasted time when the node is running but no task work is being done

Implementation Issues:
- [x] #143 
- [x] #215 
- [x] #216 
- [x] #220 
- [x] #144  
- [x] #145 
- [x] #149  
- [ ] #150 
- [x] #151 
- [x] #245
- [x] #246  
- [x] #279 
- [x] #437 
- [x] #439 
- [x] #440 
- [x] #438 

```[tasklist]
### Tasks
```

**Comment by MattMcL4475** [comment]
Also the "Metadata Requirements" (private link)
