### ISSUE TITLE
Execute Task commands via the Runner

### ISSUE THREAD

**Issue by giventocode** [microsoft/ga4gh-tes#151]
**Overview**
The TES Task runner has the capability to create a docker container and execute the command on the container using the Docker API. The goal of this story is to integrate this capability with the TES scheduler and add required functionality if needed.'

*AC:*

- Must avoid using the docker container instance and instead using the docker API.
- Must handle the ability to download a container image, for both public container registries and CRs requiring authentication.
- Must delete the container after its execution.
- Must refactor the existing code base execute the task commands via the runner.
- Must return logs from the execution.
- Must add options using the IOptions pattern in the scheduler if required. 

*DoD:*
- Code merged into main, with unit tests for the new functionality, integration tests pass.
- Documented new options if required.

**Comment by BMurri** [comment]
Non-public container registry authentication is now required.
