### ISSUE TITLE
Store workflow execution trace in user's storage account

### ISSUE THREAD

**Issue by olesya13** [microsoft/ga4gh-tes#173]
**Problem:**
We collect information about TesTask and store it as json in PostgreSQL database. This information might be useful for debugging, workflow performance tuning, etc, but it is not accessible for user when it's stored in database.

**Solution:**
Store TesTask information in user's storage account. 

At this moment for each workflow run we generate 3 files in container 'outputs': metadata.json, outputs.data, timing.html. We might create one more file trace.json that will contain all TesTasks for that workflow run.

In Scheduler.cs (OrchestrateTesTasksOnBatch) when tesTask changes state to terminal state (completed, failed) we append tesTask to trace.json as JSONL.

**Additional context**
This work overlaps with the work required for having TES as a self-contained executable.  Requires discussion of implementation details to fit into future work on self-contained executable.

**Comment by BMurri** [comment]
TES doesn't have scope for workflow-level features. This looks like an issue that should instead be in the [microsoft/CromwellOnAzure](https://github.com/microsoft/CromwellOnAzure) repo instead (`TriggerService`, specifically, which creates those three files mentioned and has access to the `TesTasks` in the `PostgreSQL` db).

**Comment by MattMcL4475** [comment]
Possible solution: #360

**Comment by BMurri** [comment]
More task information is presented to cromwell (so workflows failed by failing tasks now have execution failure metadata provided both to cromwell's caller(s) as well as in cromwell's workflow logs. This information includes links (without SAS tokens) to trace logs from task executions that are today stored in the user's storage account.
