### ISSUE TITLE
Migrate from deprecated Microsoft.Azure.* packages to Azure.* packages

### ISSUE THREAD

**Issue by ashanhol** [microsoft/ga4gh-tes#206]
CoA Issue: https://github.com/microsoft/CromwellOnAzure/issues/646
**Problem:**
We're currently using Microsoft.Azure.* packages, many of which are deprecated.

**Solution:**
Migrate to Azure.* packages.

**Additional context**
Packages used: 
- Microsoft.Azure.Management.ApplicationInsights
  - Alt: Unknown
- Microsoft.Azure.Management.Batch
  - Alt: Azure.ResourceManager.Batch
- Microsoft.Azure.Management.Compute
  -  Alt: Azure.ResourceManager.Compute
- Microsoft.Azure.Management.ContainerService
  - Alt: Azure.ResourceManager.ContainerService
-  Microsoft.Azure.Management.Fluent
   - Alt: Azure.ResourceManager
- Microsoft.Azure.Management.KeyVault
   - Alt: Azure.ResourceManager.KeyValut
- Microsoft.Azure.Management.Network
   - Alt: Azure.ResourceManager.Network
- Microsoft.Azure.Management.PostgreSQL
   - Alt: Azure.ResourceManager.PostgreSql
- Microsoft.Azure.Management.ResourceGraph
   - Alt: Azure.ResourceManager.ResourceGraph
- Microsoft.Azure.Services.AppAuthentication
   - Alt: Azure.Identity

**Comment by ashanhol** [comment]
**Update**
We were confused as to how `DefaultStorageAccessProvider.cs` could be using `Microsoft.WindowsAzure.Storage.Blob` when the `WindowsAzure.Storage` package wasn't being included in our Nuget packages at all. Turns out it's used by something that's used by `Microsoft.Azure.Management.Fluent`, which we are including. 
It's likely that moving away from the deprecated packages will be a mess of unraveling things like this.

**Comment by BMurri** [comment]
We really do need to migrate away from all deprecated packages. We're using way too many of them from Azure. There will be some pain involved.

**Comment by ashanhol** [comment]
Good news everyone! The Azure sdk has migration guides!
Here's one for blob: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/AzureStorageNetMigrationV12.md

Here's one for Azure.ResourceManager https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/docs/MigrationGuide.md

**Comment by BMurri** [comment]
Fixed via #744
