### ISSUE TITLE
TES should always upload stdout and stderr

### ISSUE THREAD

**Issue by MattMcL4475** [microsoft/ga4gh-tes#212]
Currently, when a TES task succeeds, stdout and stderr are not uploaded.  This might be a Batch config setting.

It's expected that stdout and stderr are always uploaded.

**Comment by BMurri** [comment]
fixed via #322

**Comment by BMurri** [comment]
This appears to have regressed.

I have a partial fix ready, which I'll provide today.

**Comment by BMurri** [comment]
I'm reopening a more appropriate issue for this regression.
