### ISSUE TITLE
[#7 TES 1.1 Spec compliance] Validate the response against filter-1

### ISSUE THREAD

**Issue by BMurri** [microsoft/ga4gh-tes#250]
**Describe the bug**
TES does not implement the new filter added in TES 1.1 list tasks

**Steps to Reproduce**
Run the TES compliance test for TES 1.1

**Expected behavior**
The `Filter-1` test case passes.

**Additional context**
Currently, the test case message says: `Filter-1 failed for GET /tasks due to invalid filter type`

**Comment by MattMcL4475** [comment]
related #342
