### ISSUE TITLE
TES internal files not configured for Terra for uploading TES runner and storing the supported-vm-sizes

### ISSUE THREAD

**Issue by MattMcL4475** [microsoft/ga4gh-tes#275]
When in Terra, all the code that uses "defaultStorageAccountName" should use: `TerraOptions.WorkspaceStorageAccountName`.
"TesExecutionsPathPrefix" should be set by a new property in `TerraOptions`, that Terra should set to a value like: "WorkspaceStorageContainerName/workspace-services/cbas/APPID/tes-internal"

1.  [supported-vm-sizes](https://github.com/microsoft/ga4gh-tes/blob/243a4aaa0b08fcbf7dacc366a0bdd53d633dd250/src/TesApi.Web/ConfigurationUtils.cs#L74)

This doesn't work in Terra.  Need to use defaultStorageAccountName with TesExecutionsPathPrefix

2.  https://github.com/microsoft/ga4gh-tes/blob/243a4aaa0b08fcbf7dacc366a0bdd53d633dd250/src/TesApi.Web/BatchScheduler.cs#L373

This also doesn't work in Terra for the same reason

![image](https://github.com/microsoft/ga4gh-tes/assets/23408335/f1c41864-9371-455b-a9ce-30199c956e19)

**Comment by BMurri** [comment]
Since this makes "TesExecutionsPath" store three types of data (up from two), I'm going to add the following root directories to the `tes-internals` container (and by extension, this new property):
* Binaries
* Configuration
* Tasks
