### ISSUE TITLE
[#148 Implement TES Task Runner]Private container registry handling through the runner

### ISSUE THREAD

**Issue by ngambani** [microsoft/ga4gh-tes#279]
Motivation to prioritize this: vmsizes that are gen-2 capable are prone to failures in various different ways due to the fact that batch does not have any gen-2 approved images for workloads using containers.

* Increasing security by no longer placing credentials in plain view in the azure pool configuration by placing tes-runner in full control of handing all phases of the interactions with the container registries.
* Improving reliability for Gen2 VMSizes when running in Azure Batch by enabling the docker settings to be fixed BEFORE they are used.
* Improving performance by reducing the time required to queue a TesTask into Azure Batch, while also reducing network traffic and Azure management API calls.

Note: the implementation does NOT work with customizing ACR domain names.

**Comment by jsaun** [comment]
Currently we are providing the ACR admin username and password to Batch https://github.com/microsoft/ga4gh-tes/blob/4.6.0/src/TesApi.Web/BatchScheduler.cs#L1470, when we implement with the TesRunner we should use managed identity instead.

**Comment by BMurri** [comment]
One file was missed
