### ISSUE TITLE
Deployment test task fails in main

### ISSUE THREAD

**Issue by MattMcL4475** [microsoft/ga4gh-tes#328]
**Describe the bug**
When running deploy-tes-on-azure.exe on Windows locally, get the following error:

"system_logs": [ "UnknownError", "Microsoft.WindowsAzure.Storage.StorageException: The specified container does not exist.", "   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.UploadFromStreamAsyncHelper(Stream source, Nullable`1 length, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext, IProgress`1 progressHandler, CancellationToken cancellationToken)\n   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()\n--- End of stack trace from previous location ---\n   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)\n   at Polly.AsyncPolicy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)\n   at TesApi.Web.Management.CacheAndRetryHandler.ExecuteWithRetryAsync(Func`1 action) in D:\\a\\_work\\1\\s\\src\\TesApi.Web\\Management\\CacheAndRetryHandler.cs:line 121\n   at TesApi.Web.Storage.StorageAccessProvider.UploadBlobAsync(String blobRelativePath, String content) in D:\\a\\_work\\1\\s\\src\\TesApi.Web\\Storage\\StorageAccessProvider.cs:line 59\n   at TesApi.Web.BatchScheduler.ConvertTesTaskToBatchTaskAsync(String taskId, TesTask task, Boolean poolHasContainerConfig, Int32 vmVCpusAvailable) in D:\\a\\_work\\1\\s\\src\\TesApi.Web\\BatchScheduler.cs:line 1020\n   at TesApi.Web.BatchScheduler.AddBatchTaskAsync(TesTask tesTask) in D:\\a\\_work\\1\\s\\src\\TesApi.Web\\BatchScheduler.cs:line 543" ]

**Comment by BMurri** [comment]
@MattMcL4475 was this resolved?
