### ISSUE TITLE
"Total reclaimed space: 0B" after deleting images

### ISSUE THREAD

**Issue by MattMcL4475** [microsoft/ga4gh-tes#350]
**Describe the bug**
Even though images have been deleted, it says "Total reclaimed space: 0B".  Unclear if the log message has a bug, OR, if no space was actually reclaimed.

```
docker.io/library/ubuntu:latest
Starting download operation.
<6>2023-08-09 23:05:46.598 Tes.Runner.Executor[0] No inputs provided
Total bytes transfer: 0
18593e9f-68e4-43a6-b4f6-10b85ebc73d0
Starting upload operation.
<6>2023-08-09 23:05:47.936 Tes.Runner.Executor[0] No outputs provided
Total bytes transfer: 0
Task complete.
Untagged: ubuntu:latest
Untagged: ubuntu@sha256:0bced47fffa3361afa981854fcabcd4577cd43cebbb808cea2b1f33a3dd7f508
Deleted: sha256:5a81c4b8502e4979e75bd8f91343b95b0d695ab67f241dbed0d1530a35bde1eb
Deleted: sha256:59c56aee1fb4dbaeb334aef06088b49902105d1ea0c15a9e5a2a9ce560fa4c5d
Total reclaimed space: 0B
Total reclaimed space: 0B
```

**Steps to Reproduce**

`curl -u "tes:REMOVED" -H "Content-Type: application/json" -X POST -d '{"executors":[{"image":"ubuntu","command":["cat /proc/sys/kernel/random/uuid"]}]}' "https://REMOVED.eastus.cloudapp.azure.com/v1/tasks"`

**Expected behavior**
The number of bytes reclaimed by deleting the image(s).

**Comment by BMurri** [comment]
> Task complete.

`docker rmi ubuntu -f`
> Untagged: ubuntu:latest
> Untagged: ubuntu@sha256:0bced47fffa3361afa981854fcabcd4577cd43cebbb808cea2b1f33a3dd7f508
> Deleted: sha256:5a81c4b8502e4979e75bd8f91343b95b0d695ab67f241dbed0d1530a35bde1eb
> Deleted: sha256:59c56aee1fb4dbaeb334aef06088b49902105d1ea0c15a9e5a2a9ce560fa4c5d

`rm -fdr wd/wd`
`sudo docker container prune -f`
> Total reclaimed space: 0B

`sudo docker system prune -a --volumes -f`
> Total reclaimed space: 0B

What is happening is that there was only one image that was ever loaded by docker. The `docker rmi` command happened to remove all the filesystem assets related to both the container and the image. That command does NOT tell how much filesystem space was reclaimed with the default logging level of `info`. The only level more verbose is `debug`, but that spits out a LOT more usually useless information when all you really want to know is that the operation succeeded.

The other two docker commands are intended to ensure that, based on anything that might have happened while the executor ran, there wasn't some other artifact that had been left on the disk from the task.

My preference would be to close this as `not planned` but leaving this open in case either the team or the community would prefer something added that will contextualize the messages the tools are generating.

**Comment by MattMcL4475** [comment]
Good idea to echo the commands right before running them.  Thanks @BMurri

**Comment by ngambani** [comment]
@MattMcL4475 Should this fall under the TES P1, P2 or P3 issues?

**Comment by BMurri** [comment]
No longer relevant as node runner has replaced the previous cleanup script
