### ISSUE TITLE
AllocationFailed: The selected VM size 'Standard_D1_v2' cannot boot Hypervisor Generation '2'.

### ISSUE THREAD

**Issue by BMurri** [microsoft/ga4gh-tes#43]
**Describe the bug**
In some azure locations (including the location we run our integration tests), we are seeing `vmsize`s that are not compatible with our default compute node images.

**Steps to Reproduce**
Create a PR.

**Expected behavior**
All eligible sizes should work with the configured image(s).

**Deployment details: (any information you can provide would be helpful):**
 - OS: n/a
 - Version: 3.3 & 4.0 (not yet released)
 - Any notable Azure customizations and/or configurations: none

**Example Error from Batch Account (Azure Portal)**

> Code: AllocationFailed Message:
> Desired number of low priority nodes could not be allocated Values:
> Provider Error Json - {
>   "error": {
>     "code": "BadRequest",
>     "message": "The selected VM size 'Standard_D1_v2' cannot boot Hypervisor Generation '2'. If this was a Create operation please check that the Hypervisor Generation of the Image matches the Hypervisor Generation of the selected VM Size. If this was an Update operation please select a Hypervisor Generation '2' VM Size. For more information, see [https://aka.ms/azuregen2vm](https://aka.ms/azuregen2vm)"
>   }
> }
> Provider Error Json Truncated - False

**Additional context**
There is a reason we changed the default image from a gen_1 to a gen_2, but I don't recall the exact specifics at the moment.

The public price API doesn't indicate with which generation each `vmsize` is compatible. The management-plane APIs we previously used didn't provide the same names (so we created an internal "allow list" we had to maintain for each release that could very well become out of date the day we release).

The only APIs that indicate which images are gen_1 or gen_2 and the only APIs that indicate which generations each `vmsize` is compatible are all in the management-plane.

Note that, while we don't expose the default image in either deployer, they can be changed by altering the configuration and running an update with the deployer.

Note also, that the not-yet fully implemented "host configuration" feature overrides/replaces the configured default image with the configured image from the host-configuration metadata (if supplied).

Some possible solutions without (re)adding more management-plane API calls:
| Whitelist | Single Gen | Description |
|:---------:|:----------:| ----------- |
| no | no | Change the current default image properties to two, one for each generation, when one image produces errors for the initial node, replace the pool with the another one using the other image. |
| no | yes | Essentially do nothing. |
| yes | no | Restore a white list encoding the generational compatibility, change the current default image properties to two, one for each generation. |
| yes | yes | Restore a white list, restricting to a single generation, |

I'm not a fan of returning to the whitelist, and I don't like the idea of verifying that the two images selected by the user actually target different generations (reintroducing management-plane operations) because _if they change our defaults, it's their problem_, so my preference would be the per-generation image properties + trying one, and dropping that pool/replacing it with another using the other image idea (the top line in the table above)

**Comment by jsaun** [comment]
Closed in #52
