### ISSUE TITLE
[#148 Implement TES Task Runner] Event publishing by the TES runner

### ISSUE THREAD

**Issue by giventocode** [microsoft/ga4gh-tes#437]
**Problem.**
The TES server cannot access the status of Task processing except through the Batch APIs. This causes delays in completing tasks. The Batch APIs often mark Job/Tasks as completed much later than their actual completion time. Moreover, querying the Batch API for state leads to throttling issues and more delays when scaling up

**Solution:**
The TES runner controls the execution of all the steps in the Batch node. It can generate events that describe the execution and send them to a sink/destination for consumption.

**AC:**
  -  Events must be published to a storage account 
    - This will mitigate the need for additional infrastructure to run TES on Azure and Terra.
    - Must faciliate manual and programmatic discovery/consumption of the messages.
      -  Must use the following path-pattern to publish the events:
          -  /tes-internal/events/{event-name}/YYYY/MM/DD/{timestamp}{workflow_id}{task_id}.json
      - Must set tags in each blob for: {task_id}, {workflow_id}, {event_name} and {created}.
         - Created tag must use HTTP GET friendly format, e.g. [ISO 8601](http://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations) 
  - Must create events for the following actions: download start/end, execution start/end, upload start/end and completion.
    - Download and upload events must include number of files and total bytes transferred. 
    - Completion event must indicate success or failure. 
  - Events must follow the same schema,  and enable correlation to the tasks and workflows.

**Comment by ngambani** [comment]
@giventocode can we link this issue to the TES runner https://github.com/microsoft/ga4gh-tes/issues/148? Or should this be separate from the runner implementation?
