### ISSUE TITLE
[#148 Implement TES Task Runner] Make file names consistent for the runner binary, its task definition file and server TES task.

### ISSUE THREAD

**Issue by giventocode** [microsoft/ga4gh-tes#439]
**Problem:**
The runner’s binary file name is tRunner, while the node task definition file name is TesTask.json. These file names follow inconsistent naming conventions. Also, TesTask is an inaccurate name because it suggests that it is the task sent to the TES server. The TES server also uploads a serialized version of the TesTask model using the file name  ServerTesTask.json. 
 
**Solution:**
Rename files following Linux style naming convention and using descripted names.

**AC:**
  -  Runner's binary file name: tes-runner, 
  -  Node task definition file name: runner-task.json
  -  Server TES task model: server-tes-task.json

**Comment by ngambani** [comment]
@giventocode can we link this issue to the TES runner https://github.com/microsoft/ga4gh-tes/issues/148? Or should this be separate from the runner implementation?
