### ISSUE TITLE
[#148 Implement TES Task Runner] Optimize calls to WSM when executing tasks via the runner

### ISSUE THREAD

**Issue by giventocode** [microsoft/ga4gh-tes#440]
**Problem:**
Each input and output requires a WSM call to obtain the SAS token. However, the WSM API may fail to respond under stress conditions, such as when running large scatter-gather workflows.

**Solution:**
To reduce the frequency of WSM calls, by caching the SAS tokens while executing a node task.

**AC:**
- Use container scoped JIT tokens in the runner to improve caching performance for both reading and writing operations.
- Manage possible expiration scenarios, even though they are rare due to the JIT nature of the tokens.
- Implementation in the URL transformation strategy for Terra.

**Comment by ngambani** [comment]
@giventocode can we link this issue to the TES runner https://github.com/microsoft/ga4gh-tes/issues/148? Or should this be separate from the runner implementation?
