### ISSUE TITLE
Upload operations are failing

### ISSUE THREAD

**Issue by giventocode** [microsoft/ga4gh-tes#448]
**Describe the bug**
Runner running in CoA, is failing to upload with following exception:

Tes.Runner.Transfer.BlobBlockApiHttpUtils[0] Error executing request System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (This request is not authorized to perform this operation using this permission.).    at Tes.Runner.Transfer.BlobBlockApiHttpUtils.HandleHttpRequestException(Nullable`1 status, HttpRequestException ex)    at Tes.Runner.Transfer.BlobBlockApiHttpUtils.ExecuteHttpRequestImplAsync(Func`1 request, CancellationToken cancellationToken) <3>2023-10-05 06:47:23.761 Tes.Runner.Transfer.PartsProcessor[0] Failed to execute processorAsync System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (This request is not authorized to perform this operation using this permission.).    at Tes.Runner.Transfer.BlobBlockApiHttpUtils.HandleHttpRequestException(Nullable`1 status, HttpRequestException ex)

**Expected behavior**
No error.

**Comment by MattMcL4475** [comment]
Let's implement the ProcessExitCode for this
