### ISSUE TITLE
Automatically create partition for NVMe disks and use it for images, I/O, and executor Docker volume

### ISSUE THREAD

**Issue by MattMcL4475** [microsoft/ga4gh-tes#454]
**Problem:**
Azure L-series VMs have NVMe drives with no mountpoint.  TES tasks should use these by default if they exist.

**Solution:**
The runner should check if NVMe disks exist, and if so, create a single mountpoint (use RAID0 if more than one disk) in the TES runner.  Use it for Docker image storage, input/output storage, and the main volume for the TES executor.  Consider reformatting every time on task start, so that the previous run is securely deleted (`rm` only removes file references) if more than one task runs on the same machine.  Here is an example of a `Standard_L16S_v3` on startup:

![image](https://github.com/microsoft/ga4gh-tes/assets/23408335/459a0d48-d42b-4828-ae7c-2c936b189caf)

**Comment by BMurri** [comment]
Possibly related to work previously targeting microsoft/CromwellOnAzure#317
