### ISSUE TITLE
Add LowPriority prices to BatchSupportedVmSizeInformation.json and use default file if pricing API fails

### ISSUE THREAD

**Issue by MattMcL4475** [microsoft/ga4gh-tes#476]
**Describe the bug**
`BatchSupportedVmSizeInformation.json` does not contain items for LowPriority VMs, and also, if the pricing API fails, TES is failing and not using the default files.

**Expected behavior**
TES should always use `BatchSupportedVmSizeInformation.json`, unless its able to get better info from the pricing API.  Failures with the price API should never result in TES workflow failures.

**Comment by MattMcL4475** [comment]
Also let's update `BatchSupportedVmSizeInformation.json` to the latest info

**Comment by BMurri** [comment]
@jsaun Was this fixed via #481

**Comment by MattMcL4475** [comment]
@jsaun any update on this one?

**Comment by jsaun** [comment]
@MattMcL4475 Yeah, this was fixed in the PR Blair mentioned, closing now.
