### ISSUE TITLE
Possible regression

### ISSUE THREAD

**Issue by BMurri** [microsoft/ga4gh-tes#544]
**Describe the bug**
When support was added for CWL files run through Cromwell three or so years ago, TES and Cromwell shared a volume mount (`\cromwell-tmp`) and code was added to TES because Cromwell would supply TES inputs where the `url` was of the form `file:///cromwell-tmp/tmp12345/blob1`.

When we added K8 deployments we did not preserve that volume mapping for TES, and when we subsequently removed support for VM CoA deployments, those inputs would now fail.

Cromwell has now removed support for CWL, but I don't know the history well enough to know if these types of inputs only happen(ed) with CWL, or if Cromwell fixed their code to no longer send inputs pointing to their "tmp" space, or if we're just waiting on latent bug.

**Comment by MattMcL4475** [comment]
@jgainerdewar do you know if `\cromwell-tmp` should always be available for Cromwell to function properly?  Thank you!

**Comment by BMurri** [comment]
To clarify, the cromwell containers currently have that path mounted to a kubernetes-provided storage of helm-configurable size `32Gi`. The question is if the TES containers need to have the same storage (abet read-only) also available when using the configuration found [here](https://github.com/microsoft/CromwellOnAzure/blob/40c56db7650fdecabbee5e12faaa0e9ddf92ace4/src/deploy-cromwell-on-azure/scripts/cromwell-application.conf) because of the possibility of URLs of the form described above.

**Comment by jgainerdewar** [comment]
I wouldn't expect Cromwell to send TES paths from its tmp directory. Any files that Cromwell creates to be used as task inputs should be written to the execution directory, which will be in blob storage (perhaps mounted via blobfuse). I just double-checked and confirmed that, for example, the result of a `write_lines` engine function is written to the per-task execution directory.
