### ISSUE TITLE
Default storage provider does not throw exceptions when local path to Sas URL parsing fails

### ISSUE THREAD

**Issue by giventocode** [microsoft/ga4gh-tes#56]
The `MapLocalPathToSasUrlAsync` implementation of the `DefaultStorageProvider` returns `null` and logs an error when the parsing fails.  This behavior makes it hard to debug and identify issues.

AC:
 - Throw exceptions when parsing fails with relevant error information and log errors.

**Comment by ngambani** [comment]
@giventocode is this already fixed?
