### ISSUE TITLE
iptables occasionally reports "Another app is currently holding the xtables lock"

### ISSUE THREAD

**Issue by MattMcL4475** [microsoft/ga4gh-tes#682]
**Describe the bug**
A rare transient error can appear that results when xtables is locked.  iptables error is "Another app is currently holding the xtables lock. Perhaps you want to use the -w option?".  This results in the task failing.

**Steps to Reproduce**
Transient

**Expected behavior**
It should wait for up to 30s for the transient issue to resolve itself

**Comment by BMurri** [comment]
closed via #681
