### ISSUE TITLE
Dockerfile-Tes fails to build

### ISSUE THREAD

**Issue by colin-nolan** [microsoft/ga4gh-tes#72]
**Describe the bug**
`src/Dockerfile-Tes` fails to build.

Note: I don't think it's documented anywhere how an image for this service should be built. In lieu of a published image (https://github.com/microsoft/ga4gh-tes/issues/3) I have _assumed_ `./src/Dockerfile-Tes` builds such an image but this may be wrong. Thus perhaps I shouldn't expect this to work if it's for a different use case!

**Steps to Reproduce**
```
$ DOCKER_BUILDKIT=0 docker build -f src/Dockerfile-Tes -t ga4gh-tes src
Sending build context to Docker daemon  1.702MB
Step 1/16 : FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
 ---> 543d806aedf7
Step 2/16 : WORKDIR /app
 ---> Using cache
 ---> fecd7ee10057
Step 3/16 : COPY TesApi.Web/TesApi.Web.csproj TesApi.Web/
 ---> Using cache
 ---> fda3cc58152b
Step 4/16 : COPY Tes/Tes.csproj Tes/
 ---> Using cache
 ---> c7e57afcb7cf
Step 5/16 : RUN dotnet restore TesApi.Web/TesApi.Web.csproj
 ---> Using cache
 ---> 49e6c5ef900e
Step 6/16 : COPY . ./
 ---> 5ceeb23cf77d
Step 7/16 : RUN dotnet publish -c Release -o out --no-restore TesApi.Web/TesApi.Web.csproj
 ---> Running in c80cae778d86
MSBuild version 17.4.1+9a89d02ff for .NET
/usr/share/dotnet/sdk/7.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1004: Assets file '/app/CommonUtilities/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/app/CommonUtilities/CommonUtilities.csproj]
  Tes -> /app/Tes/bin/Release/net7.0/Tes.dll
The command '/bin/sh -c dotnet publish -c Release -o out --no-restore TesApi.Web/TesApi.Web.csproj' returned a non-zero code: 1
```

**Expected behavior**
The image builds without further knowledge or actions on the developer's side.

This works but I have no modern knowledge of how C# projects are set up, and therefore I don't know what the consequences are (perhaps the `--no-restore` is there to pin the dependency versions down and that JSON file should actually be checked in?):
```
diff --git a/src/Dockerfile-Tes b/src/Dockerfile-Tes
index fe32275..4ade248 100644
--- a/src/Dockerfile-Tes
+++ b/src/Dockerfile-Tes
@@ -11,7 +11,7 @@ RUN dotnet restore TesApi.Web/TesApi.Web.csproj

 # Copy the rest of the files and publish
 COPY . ./
-RUN dotnet publish -c Release -o out --no-restore TesApi.Web/TesApi.Web.csproj
+RUN dotnet publish -c Release -o out TesApi.Web/TesApi.Web.csproj

 # Build runtime image
 FROM mcr.microsoft.com/dotnet/aspnet:7.0
 ```

**Deployment details: (any information you can provide would be helpful):**
 - OS: Any, where a build is attempted from a fresh checkout
 
**Screenshots**
n/a

**Additional context**
n/a

**Comment by MattMcL4475** [comment]
https://github.com/microsoft/ga4gh-tes/pull/122

**Comment by MattMcL4475** [comment]
Colin, thanks for reporting this!  The 4.0.0 image is available here: https://github.com/microsoft/ga4gh-tes/releases/tag/4.0.0
