### ISSUE TITLE
Empty/whitespace shall have same effect as null in Tes.Input.URL / Content

### ISSUE THREAD

**Issue by MattMcL4475** [microsoft/ga4gh-tes#742]
**Describe the bug**
If a TES task has " " or "" set for the Content or URL, it could cause a BadRequest, even if it's inconsequential.

**Steps to Reproduce**
Create a TES task and set the input.Content to empty/whitespace and the input.URL to a real value.

**Expected behavior**
It should be inconsequential.

**Comment by BMurri** [comment]
I would argue that whitespace in Content is consequential, but empty should be treated the same as null.

**Comment by MattMcL4475** [comment]
Leaving as is to allow creation of empty files
