### ISSUE TITLE
[# 7 TES 1.1 Spec compliance] allow wildcards in output paths 

### ISSUE THREAD

**Issue by vsmalladi** [microsoft/ga4gh-tes#8]
allow wildcards in output paths [tesOutput.path](https://github.com/ga4gh/task-execution-schemas/blob/117cd927aa119469ee80cedbd8940c968b81c5d6/openapi/task_execution_service.openapi.yaml#L537)

**Comment by vsmalladi** [comment]
@BMurri  can we close this?

**Comment by BMurri** [comment]
This is partially implemented. A complete implementation is not currently planned.
