### ISSUE TITLE
[# 7 TES 1.1 Spec compliance]  Making file type an optional argument 

### ISSUE THREAD

**Issue by vsmalladi** [microsoft/ga4gh-tes#9]
Making file type an optional argument [tesInput.type](https://github.com/ga4gh/task-execution-schemas/blob/117cd927aa119469ee80cedbd8940c968b81c5d6/openapi/task_execution_service.openapi.yaml#L435)

**Comment by vsmalladi** [comment]
@MattMcL4475  is this already optional now: [File Type](https://github.com/microsoft/ga4gh-tes/blob/5073c6a97942e1a13643fcb2b22b9a483431ca1c/src/Tes/Models/TesInput.cs#L146)

**Comment by vsmalladi** [comment]
Closing

**Comment by BMurri** [comment]
fixed via #673 and #788
