### ISSUE TITLE
Create a default ACR and always use it for all images

### ISSUE THREAD

**Issue by MattMcL4475** [microsoft/ga4gh-tes#91]
Currently, if you are using a publicly available executor image, then Batch will run the command script directly on the node.

However, if you are using an executor image in a private ACR, you have to supply the username and password to the ACR using the Batch "Container Configuration".  Once the Container Configuration is set, Batch REQUIRES that you specify a Docker image to run your command script.  Therefore, that image must have Docker already installed in it.   

Future improvement: ALWAYS use ACR images for ALL executor images, including the "docker" image.  This will also prevent Dockerhub throttling.

To do this: 

1.  The Deployer would always create an Azure Container Registry on initial deployment
2.  When a WDL is run, if an image is NOT in your ACR, get the latest SHA for the image (even if it's MCR), then look if the SHA exists in the Azure Container Registry.  If it does not, then call the "ImportImageAsync" SDK call from the ContainerRegistryClient and use that
3.  Periodically delete old images in the ACR, or else the ACR will quickly fill up.  Look into possibly using a scheduled ACR task for this, if it's possible for it to query for old images (https://learn.microsoft.com/en-us/azure/container-registry/container-registry-tasks-scheduled)

**Comment by BMurri** [comment]
https://learn.microsoft.com/en-us/azure/container-registry/container-registry-auto-purge

**Comment by MattMcL4475** [comment]
This would be better: https://github.com/microsoft/ga4gh-tes/issues/209
