### ISSUE TITLE
Use Azure Batch simplified compute node communication for private networking. 

### ISSUE THREAD

**Issue by jsaun** [microsoft/ga4gh-tes#97]
https://learn.microsoft.com/en-us/azure/batch/simplified-compute-node-communication

The current method of disabling public ips on Batch nodes is being disabled on March 31. 
https://learn.microsoft.com/en-us/azure/batch/batch-pool-no-public-ip-address

We need to migrate to simplified node communication for pools without public ips at least. In addition, using the new simplified node communication model for all pools looks like it makes sense also.

**Comment by MattMcL4475** [comment]
"Create new pools with the `targetNodeCommunicationMode` set to `simplified` and validate that the new pools are working correctly. Migrate your workload to the new pools and delete any earlier pools."

**Comment by MattMcL4475** [comment]
Setting the Simplified mode would go here:

![image](https://user-images.githubusercontent.com/23408335/219881981-100cdefa-601d-4588-9e43-365006b5e06e.png)
