### ISSUE TITLE
Uncommon IOptions usage pattern

### ISSUE THREAD

**Issue by BMurri** [microsoft/ga4gh-tes#99]
**Describe the bug**
IOptions is only used to "group" and to ease parsing of configuration. Its purported purpose is validation and live updating.

**Steps to Reproduce**
Except for logging, take any of the configuration using IOptions. Update any property. Note that the configuration change has no effect without rebooting.

**Expected behavior**
IOptions configurations should be both validated and able to be live updated.

**Comment by MattMcL4475** [comment]
Do AKS config changes update the environment variables in real-time without restarting the container?

**Comment by BMurri** [comment]
Covered by #98 & #100
